config/routes.rb
Rails.application.routes.draw do
  root 'calculator#show'
  post 'calculate', to: 'calculator#calculate'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/calculator_controller.rb
class CalculatorController < ApplicationController
  include CalculatorHelper

  def show
    @answer = answer_params[:answer]
  end

  def calculate
    answer = evaluate_expression(calculation_params[:expression])
    rounding_param = answer.to_i == answer ? 0 : 2 # this makes sure integers are shown without any decimals
    answer = answer.round(rounding_param)
    redirect_to root_path(answer: answer)
  end

  private

  def answer_params
    params.permit(:answer)
  end

  def calculation_params
    params.permit(:expression)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/calculator_helper.rb
module CalculatorHelper

  def evaluate_expression(expression)
    numbers = expression.split(/[*\/+-]/).map(&:to_i)
    operators = expression.split(/\d+/).delete_if(&:blank?)
    %w(* / + -).each do |symbol|
      operators.count(symbol).times do
        operator_index = operators.index(symbol)
        a = numbers[operator_index].to_f
        b = numbers[operator_index + 1].to_f
        numbers[operator_index] = a.send(symbol, b)
        numbers.delete_at(operator_index + 1)
        operators.delete_at(operator_index)
      end
    end
    numbers.first
  end

end

app/views/calculator/show.slim
h1 Calculator

= form_tag calculate_path, method: :post do
  = label_tag(:expression, "Expression:")
  = text_field_tag(:expression)
  = submit_tag 'Calculate'

h2 = @answer

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CalculatorRails</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>